# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 794c4c941382e3cbf8aa7530549583e51e26a16d0df898a51fd7bc71c9b8c9f622367d513de1a02990212f9a8e7f576fedb42e5552d38fd55be734f93b901cea

test:
  secret_key_base: 7fbe94269dcd56b69137f3c1bfc30bb2fa879ab4197d00049b0768b9cfe1a23509bf67ef04d3f7ba15f246236eb8b6d8ceb3847941684289d0735106bd6b98ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
